#
# This Dockerfile generated by createLabelFile.py
# It reads 'DockerfileNoLabels' and then adds
#  some generated label entries
#
# <DockerfileNoLabels>
FROM haugene/transmission-openvpn:latest

ARG container_locale=en_US.UTF-8 
ARG container_language=en_US.en

RUN  apt-get -qqq update  > /dev/null \
    && apt-get -qqq -y install supervisor net-tools lsof inotify-tools python3-pip python3 locales nginx nano > /dev/null \
    && echo .... \
    && echo "Locales ($container_locale - $container_language)" \
    && echo .... \
    && locale-gen $container_locale \
    && update-locale LANG=$container_locale LC_ALL=${container_locale} \
    && cat /etc/default/locale \ 
    && mkdir -p -v /var/log/supervisor \
    && pip3 install  srt humanize transmissionrpc flexget requests validators --no-cache-dir  > /dev/null\
    && rm -rf ~/.cache/pip/* \
    && apt-get -q -q clean  > /dev/null \
    && apt-get -q -q autoclean  > /dev/null \
    && ln -s /etc/transmission/environment-variables.sh /etc/profile.d/02-transmission-environment-variables.sh  \
    && chmod +x /etc/transmission/userSetup.sh
ENV LANG $container_locale 
ENV LANGUAGE $container_language 
ENV LC_ALL $container_locale 
ENV TRANSMISSION_HOME=/config/transmission 
ENV UFW_EXTRA_PORTS=9117,5050,80 
ENV XDG_CONFIG_HOME=/config 
ENV ADD_TRACKERS_INTERVAL_S=300

ADD  container/ /

EXPOSE 9117 5050 9091 80
CMD ["/bin/bash","-c","/volansmelesmeles/containerStartup.sh"]
# </DockerfileNoLabels>
#
# LABEL entries added by createLabelFile.py
#
LABEL maintainer="jon@badger.shoes"
LABEL volansmelesmeles.transmissionopenvpn.base.image.architecture="amd64"
LABEL volansmelesmeles.transmissionopenvpn.base.image.os="linux"
LABEL volansmelesmeles.transmissionopenvpn.base.image.repodigests="haugene/transmission-openvpn@sha256:bbbea5e28cd5a8b7895fd9ab27f083ed30829f884ab951f6abb9b15c5f55284c"
LABEL volansmelesmeles.transmissionopenvpn.base.image.repotags="haugene/transmission-openvpn:latest"
LABEL volansmelesmeles.transmissionopenvpn.base.image="haugene/transmission-openvpn:latest"
LABEL volansmelesmeles.transmissionopenvpn.jackett.url="https://github.com/Jackett/Jackett/releases/download/v0.16.7/Jackett.Binaries.LinuxAMDx64.tar.gz"
LABEL volansmelesmeles.transmissionopenvpn.jackett.version="v0.16.7"
